title: Sami El Sabri
author: Sami El Sabri
baseurl: ""
url: "https://samielsabri.github.io"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap

social-network-links:
  email: samielsabri@gmail.com
  linkedin: samielsabri
  github: samielsabri
